### PR TITLE
1 html for calendar

### LINKED ISSUE #1: HTML for calendar
Develop the HTML structure for the calendar interface for a single month (April 2024).

image

**Here is just a sample sketch. Would be great if you can try to make some changes to it to make it nicer.**

**Tasks:**
1. Set up the basic structure of the webpage as shown. It is encouraged to use the date picker for the same:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

3. Try to add very basic CSS to give the page some structure please do so. A different group of people will be working on actually styling it so that it looks nice.
4. Design and implement a section to display tasks associated with selected dates. Try to make the layout user-friendly.

**Considerations:**
1. Try to write clean code that is easy to understand
2. **Use comments** and put some **basic documentation in the README.md** to help people working on the CSS after you. This can be pretty short!
3. Test code before pushing changes
5. **Work on a separate branch**

**Deadline**: WED Apr 24 10:00AM (so that we have time to work on other things)

### PR DESCRIPTION
**Pull request by vishaal-gaddipati**
The code regarding issue 1 for the Calendar widget assigned to Vishaal, Drishti, and Mishka.

### CODE REVIEW

**Comment by Arnav710** [comment]
image

I think this should not be happening. Try to fix this maybe using `display` or some other option

**Comment by Arnav710** [comment]
image

Month should be centered over the calendar. Think right now it seems to be neither left of center aligned. Looks good otherwise!

**Comment by Arnav710** [comment]
image

Similar thing here, let's try to keep `Today's Tasks` in one line and center aligned

**Comment by vishaal-gaddipati** [comment]
> image
> I think this should not be happening. Try to fix this maybe using `display` or some other option

On my end it looks like this. And I think for Mishka it looked similar to this as well. I think formatting for different devices is more of a CSS issue rather than the HTML itself.
Screenshot 2024-04-24 at 12 09 03 AM

**Comment by Arnav710** [comment]
I think we can just address these styling issues in the next issue. People working on the CSS part can probably fix it. I'll merge this in.

**Comment by mishkajethwani** [comment]
> image
> I think this should not be happening. Try to fix this maybe using `display` or some other option

I think this is an issue. We just shifted it by pixels that is probably why this is happening. I'll fix it right now!

**Pull request merged**
